"""SymPy-claim → Lean 4 + Mathlib formalisation.

This is the front-end of the offline catalog verifier
(``studio/catalog_verifier.py``).  It takes a claim emitted by the
express LLM:

    {"kind": "identity" | "value",
     "description": "...",
     "a": "<SymPy expr>",
     "b": "<SymPy expr>"}

and tries to render it as a Lean 4 ``example : ... := by tac`` block
that imports the relevant Mathlib pieces.  When the claim is outside
what Mathlib + the standard tactic suite (`norm_num`, `ring`, `decide`,
`simp`) can close automatically, the translator gives up — the catalog
verifier marks the row 'unsupported' rather than guessing wrong.

Why is auto-formalisation hard?

  • The LLM emits a SymPy-syntax expression with implicit types.  Lean
    is dependently-typed: we have to commit to ``ℕ`` vs ``ℤ`` vs ``ℚ``
    vs ``ℝ`` upfront, and the right namespace for ``sin`` (``Real.sin``
    vs ``Complex.sin``).

  • Mathlib lemma names change between major versions; we target
    Lean 4 / Mathlib4 (the modern stack).

  • The right tactic depends on the claim shape:
      ``ring``     — polynomial identities over a commutative (semi)ring
      ``norm_num`` — closed numeric calculations, often with simp lemmas
      ``decide``   — decidable propositions (closed Nat, Fin, Bool)
      ``simp``     — apply rewriting lemmas to close goals

We try them in order.  The first that succeeds is the proof of record.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional


# ──────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────
_SYMPY_TO_LEAN = [
    # SymPy syntax → Lean 4 / Mathlib syntax.  Order matters.
    (r"\*\*", "^"),                     # power
    (r"\bsqrt\(", "Real.sqrt ("),       # sqrt over ℝ
    (r"\bsin\(", "Real.sin ("),
    (r"\bcos\(", "Real.cos ("),
    (r"\btan\(", "Real.tan ("),
    (r"\bexp\(", "Real.exp ("),
    (r"\blog\(", "Real.log ("),
    (r"\bln\(",  "Real.log ("),
    (r"\bpi\b",  "Real.pi"),
    (r"\bE\b",   "Real.exp 1"),
]


# Mathlib imports that the standard tactic suite needs for these
# operators.  Add to this list as the translator covers more claims.
_IMPORTS_FOR = {
    "Real.sqrt":    "import Mathlib.Analysis.SpecialFunctions.Pow.Real",
    "Real.sin":     "import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic",
    "Real.cos":     "import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic",
    "Real.tan":     "import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic",
    "Real.exp":     "import Mathlib.Analysis.SpecialFunctions.Exp",
    "Real.log":     "import Mathlib.Analysis.SpecialFunctions.Log.Basic",
    "Real.pi":      "import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic",
}


_TACTIC_ORDER = ("decide", "norm_num", "ring", "simp; ring", "ring_nf",
                 "norm_num [Real.sin_pi_div_six, Real.cos_pi_div_three]")


@dataclass
class LeanProof:
    """A candidate Lean source file."""
    imports: list[str]
    proposition: str   # body of the `example` declaration, e.g. "(a+b)^2 = a^2 + 2*a*b + b^2"
    type_ann: str      # "ℕ" | "ℤ" | "ℝ" | "Prop" | …
    tactics: list[str] # tactics to try in order

    def render(self, tactic: str) -> str:
        lines = ["-- auto-generated by studio/templates/lean_translator.py"]
        for imp in self.imports:
            lines.append(imp)
        lines.append("")
        lines.append(f"open Real Nat Int in")
        lines.append(
            f"example : ({self.proposition} : {self.type_ann}) := by {tactic}"
        )
        return "\n".join(lines) + "\n"


# ──────────────────────────────────────────────────────────────────────
# Translation
# ──────────────────────────────────────────────────────────────────────
def _detect_type(text: str) -> str:
    """Pick the most-permissive type that still admits the operators
    used.  Heuristic: Real if trig/log/sqrt/pi/e appears, else ℤ if
    minus sign appears, else ℕ.
    """
    if re.search(r"Real\.(sin|cos|tan|sqrt|exp|log|pi)", text):
        return "ℝ"
    if re.search(r"Real\.exp 1", text):
        return "ℝ"
    if "-" in text:
        return "ℤ"
    return "ℕ"


def _gather_imports(*texts: str) -> list[str]:
    needed: set[str] = set()
    for text in texts:
        for sym, imp in _IMPORTS_FOR.items():
            if sym in text:
                needed.add(imp)
    return sorted(needed)


def translate_claim(claim: dict) -> Optional[LeanProof]:
    """Return a candidate LeanProof, or None when the claim is out
    of scope for the translator."""
    if not isinstance(claim, dict):
        return None
    a = str(claim.get("a", "")).strip()
    b = str(claim.get("b", "")).strip()
    if not a or not b:
        return None
    # Reject anything with free symbolic functions / matrices for now.
    if re.search(r"Matrix\(|diff\(|integrate\(|hessian\(|Sum\(|Product\(",
                 a + b):
        return None

    lean_a = a
    lean_b = b
    for src, dst in _SYMPY_TO_LEAN:
        lean_a = re.sub(src, dst, lean_a)
        lean_b = re.sub(src, dst, lean_b)

    proposition = f"{lean_a} = {lean_b}"
    typ = _detect_type(proposition)
    imports = _gather_imports(proposition)
    # Pick a tactic ordering tuned for the type.
    if typ == "ℕ":
        tactics = ["decide", "native_decide", "norm_num", "ring",
                   "simp; ring"]
    elif typ == "ℤ":
        tactics = ["decide", "norm_num", "ring", "linarith"]
    else:   # ℝ
        tactics = ["norm_num", "ring", "ring_nf",
                   "norm_num [Real.sin_pi_div_six, "
                   "Real.cos_pi_div_three, Real.sin_pi_div_three, "
                   "Real.cos_pi_div_six, Real.sin_pi_div_four, "
                   "Real.cos_pi_div_four]"]

    return LeanProof(
        imports=imports,
        proposition=proposition,
        type_ann=typ,
        tactics=tactics,
    )
