"""Lean 4 core runtime verifier (third tier, after SymPy and Z3).

Lean is a dependently-typed theorem prover.  The kernel is a tiny
checker that, given a Lean term, certifies it has the declared type
— and the type IS the theorem.  When Lean accepts a proof, the claim
is mathematically certain at the highest rigour available in the
software.

This module uses Lean 4 *core* only — no Mathlib — so the
verification scope is narrow on purpose:

  * Closed natural-number arithmetic that the `decide` /
    `native_decide` tactic can evaluate.
  * Divisibility / gcd / lcm / mod over Nat.
  * Finite-case enumerations over Fin n.

It does NOT handle (these fall through to the previous tiers):

  * Symbolic identities with free variables (needs Mathlib's `ring`
    tactic).
  * Reals, rationals, transcendentals (no Real type without Mathlib).
  * Matrices.

Cold-start latency is ~600 ms — substantial, so this tier only fires
when SymPy AND Z3 are both inconclusive AND the claim is closed
Nat-only.

To install Lean 4 on a dev box::

    curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh \\
        -sSf | sh -s -- -y --default-toolchain stable

The Dockerfile installs the same toolchain (see "lean" stage).
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Optional


def _lean_binary() -> Optional[str]:
    """Locate the lean binary.  Prefers elan-managed install."""
    for candidate in (os.environ.get("LEAN_BIN"),
                      shutil.which("lean"),
                      str(Path.home() / ".elan/bin/lean"),
                      "/root/.elan/bin/lean",
                      "/opt/elan/bin/lean"):
        if candidate and Path(candidate).exists():
            return candidate
    return None


def is_available() -> bool:
    return _lean_binary() is not None


# ──────────────────────────────────────────────────────────────────────
# SymPy → Lean translation for Nat-only closed arithmetic
# ──────────────────────────────────────────────────────────────────────
_NAT_FUNC_MAP = {
    "Mod": "% ",
    "gcd": "Nat.gcd ",
    "lcm": "Nat.lcm ",
}


def _is_nat_closed(expr_text: str) -> bool:
    """Conservative: does the expression text use ONLY non-negative
    integer literals + (+, *, **, mod, gcd, lcm) and no symbols /
    fractions / decimal points / trig / log / pi / E / I?

    We do a string-level guard rather than an AST inspection because
    even a single Real / Symbol means Lean-core can't decide it.
    """
    text = expr_text.strip()
    if not text:
        return False
    if re.search(r"\.\d", text):    # decimal literal
        return False
    if "-" in text:
        return False    # Nat subtraction is truncating, not safe
    if "/" in text and not re.search(r"//\b", text):
        return False    # rationals
    # Strip allowed function/keyword names; anything alpha remaining
    # is a free variable or unsupported function.
    text2 = text
    for kw in ("Nat.gcd", "Nat.lcm", "Nat.mod", "Nat.div",
               "gcd", "lcm", "Mod", "mod", "Nat"):
        text2 = re.sub(rf"\b{re.escape(kw)}\b", "", text2)
    if re.search(r"[a-zA-Z_]", text2):
        return False
    return True


def _to_lean(expr_text: str) -> str:
    """Convert a SymPy-style expression to Lean syntax.

    Trivial substitutions because we only support a tiny grammar:
      ``**``  → ``^``
      ``Mod(x, y)`` → ``(x % y)``   (best-effort; if SymPy uses Mod
      we just rewrite the call into Lean's % operator).
    """
    out = expr_text.replace("**", "^")
    out = re.sub(r"\bMod\(([^,]+),\s*([^)]+)\)",
                 lambda m: f"({m.group(1).strip()} % "
                           f"{m.group(2).strip()})",
                 out)
    return out


# ──────────────────────────────────────────────────────────────────────
# Top-level
# ──────────────────────────────────────────────────────────────────────
def verify_identity(a_text: str, b_text: str,
                    *, timeout_s: float = 5.0) -> dict:
    """Try to certify a == b via Lean's `decide` over Nat.

    Returns ``{ok, reason}``:
      * ok=True            — Lean type-checked the proof.
      * ok=False, reason   — Lean rejected, or the claim is out of
                              scope for Lean core (caller should
                              fall through to the previous tier).
    """
    lean = _lean_binary()
    if lean is None:
        return {"ok": False, "reason": "lean_unavailable"}
    if not (_is_nat_closed(a_text) and _is_nat_closed(b_text)):
        return {"ok": False, "reason": "lean_unsupported:not_nat_closed"}

    src = (f"-- auto-generated by studio/templates/lean_verifier.py\n"
           f"example : ({_to_lean(a_text)} : Nat) "
           f"= ({_to_lean(b_text)} : Nat) := by decide\n")
    try:
        with tempfile.NamedTemporaryFile("w", suffix=".lean",
                                          delete=False) as fh:
            fh.write(src)
            path = fh.name
        try:
            proc = subprocess.run(
                [lean, path],
                capture_output=True, text=True,
                timeout=timeout_s,
            )
        finally:
            try:
                os.unlink(path)
            except OSError:
                pass
    except subprocess.TimeoutExpired:
        return {"ok": False, "reason": "lean_timeout"}
    except Exception as exc:  # noqa: BLE001
        return {"ok": False,
                "reason": f"lean_error:{type(exc).__name__}"}

    if proc.returncode == 0:
        return {"ok": True, "reason": ""}
    # Lean printed type-check errors → claim is wrong (or out of scope)
    # Surface the first error line as the reason.
    err = (proc.stdout + proc.stderr).strip().splitlines()
    first = next((ln for ln in err if "error" in ln.lower()),
                 (err[0] if err else "lean_unknown"))
    return {"ok": False, "reason": f"lean:{first[:120]}"}
